### ISSUE TITLE
BUG: Webpack stats object failing type validation (`Cannot load module/asset sizes.`)

### ISSUE THREAD

**Issue by westbrook-asapp** [FormidableLabs/inspectpack#110]
I'm making the jump from v0.4.0 to ^3.0.0 and when I run my application I get the following display where the application is built, but the module/asset sizes (and problems when available) are blocked from display due to errors. I checked into some similar issues (e.g. #182) in other posts, but most of them discuss development in dependencies like `inspectpack`, etc. that have since completed, so I'm at a loss.

While webpack is kind of new to me, I'm pretty comfortable saying that the below config is a bit _expansive_ so please let me know what additional or focused information I could supply to help track this issue down. Thanks!

====================================================================

###### If the issue is visual, please provide screenshots here
![image](https://user-images.githubusercontent.com/47332483/54887648-e695f300-4ed8-11e9-89e0-c4da978794b6.png)

====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

Entry script:
```
ENABLE_SOURCE_MAPS=true NODE_ENV=development webpack-dashboard -- webpack-dev-server --config webpack.config.local-dev.js --host 0.0.0.0 --no-inline
```

webpack.config.js
```
REDACTING PER MANAGEMENT :/ Let me know if there is less complete information I can share in support of finding a solution here!
```

====================================================================

###### More Details

- What operating system are you on? Mac OS
- What terminal application are you using? Terminal
- What version of webpack-dashboard are you using? @^3.0.0
- What is the output of running `echo $TERM`? xterm-256color

**Comment by ryan-roemer** [comment]
First issue: `Expecting string at modules.4.0.chunks.0.0 but instead got: null.`

```js
    {
      "id": 4,
      "identifier": "/Users/westbrookjohnson/Documents/asapp/ASAPP/js/node_modules/prop-types/index.js",
      "name": "./node_modules/prop-types/index.js",
      "index": 478,
      "index2": 475,
      "size": 1078,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        null,
        null,
        null,
        null,
        2,
        4,
        7,
        8,
        9
      ],
      // ... snipped ...
    },
```
