### ISSUE TITLE
Vulnerability introduced through yargs v11

### ISSUE THREAD

**Issue by benjaminhobbs** [FormidableLabs/inspectpack#118]
As best described here: https://app.snyk.io/test/npm/inspectpack/4.2.1

This package is using an npm dependency (yargs) that has a vulnerability. Could you please update the version of yargs you use to patch this?

PS It might be worth adding automatic vulnerability checking with Snyk.

**Comment by ryan-roemer** [comment]
Thanks for the report! Fix released in `inspectpack@4.2.2`

**Comment by benjaminhobbs** [comment]
@ryan-roemer great thanks
