### ISSUE TITLE
Exit Code for duplicates

### ISSUE THREAD

**Issue by alexander-schranz** [FormidableLabs/inspectpack#138]
I want to use `npx inspectpack -s stats.json --action duplicates` in my ci to validate if there are duplicates. For this it would be great if it would return a different exit code if it found duplicates or not. So no duplicates exit code `0` and duplicates exit code `1`.

**Comment by ryan-roemer** [comment]
Seems like a reasonable request for `--action duplicates|version` maybe with an optional `--bail` flag?
