### ISSUE TITLE
What is the difference between 「duplicate-package-checker-webpack-plugin」

### ISSUE THREAD

**Issue by Sylvenas** [FormidableLabs/inspectpack#164]
Great project !

When looking for webpack packaging duplicates, I was previously using [duplicate-package-checker-webpack-plugin](https://www.npmjs.com/package/duplicate-package-checker-webpack-plugin)， I wanted to know the key point of difference between the two.

Thanks

**Comment by ryan-roemer** [comment]
Hi @Sylvenas -- the two are pretty similar for just the webpack plugin parts. The main difference is whereas `duplicate-package-checker-webpack-plugin` gives you the on-disk information of locations of duplicates, `inspectpack`'s plugin focuses on the logical dependency view irrespective of node_modules flattening so you can more easily track down why the duplicates happened in the first place. [Here](https://github.com/FormidableLabs/inspectpack#diagnosing-duplicates) you can see an example of how this plugin provides both on-disk and logical dependencies information.

Outside of the functional differences in the plugin, the other thing this project has:

- A standalone CLI with lots of options / views
- A full test suite of various scenarios
- Support for webpack 1-5 (and tests to support)

Hope that helps your evaluation!

**Comment by ryan-roemer** [comment]
Hopefully the comment above helps. Closing this issue to focus on others!

**Comment by Sylvenas** [comment]
thanks.
