### ISSUE TITLE
Imports that are built using Webpack (using library output mode) cause errors.

### ISSUE THREAD

**Issue by Trakkasure** [FormidableLabs/inspectpack#37]
I noticed this while importing package react-draggable into my project and running tests.

I fixed by checking for unmatched empty comment filename matches and returning null. Then not pushing the modules array if the filename match was null.

The fix in my prior issue (#36) should resolve the error. But this issues is here in case that isn't added or what I suggested isn't the right way to do it.

**Comment by ryan-roemer** [comment]
Should be obviated in `inspectpack@^3` because we use stats object now, not real bundles.
