### ISSUE TITLE
BUG: Handle `Array().concat()` version of `webpackJsonp`

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/inspectpack#53]
From @ryan-codingintrigue in https://github.com/FormidableLabs/webpack-dashboard/issues/182#issuecomment-336121278

> @ryan-roemer I've been getting this error too since `1.0.0-7`. I have a pretty big SPA, so it's been hard to get a repro of the issue, but I think I've narrowed it down to something to do with my bundle splitting.
> 
> My minimal example outputs a few bundles like this:
> ```javascript
> // bundle.0.js
> webpackJsonp([0],[ ...
> // bundle.1.js
> webpackJsonp([1],{ ...
> // etc.
> ```
> However, my large SPA's bundles look like this:
> ```javascript
> // bundle.0.js
> webpackJsonp([0],Array(171).concat([
> // bundle.1.js
> webpackJsonp([1],Array(171).concat([
> ```
> 
> I haven't been able to identify why, but it looks like this is causing the inspectpack [parser/index.js#179](https://github.com/FormidableLabs/inspectpack/blob/master/lib/parser/index.js#L179) to be hit, making the parser assume throw that there "*No code sections found*"

The issue looks to be in `getJsonpModules`, where we've found a `webpackJsonp`, but expect second arg to be `[]` instead of `Array(NUM).concat([])`: https://github.com/FormidableLabs/inspectpack/blob/master/lib/parser/find-module-expression.js#L17-L22

**Comment by ryan-codingintrigue** [comment]
Given that the parameter index in `webpackJsonp` is still correct, would it be easier to add the check into `extractModules`? This seems to work for me:
```javascript
if (t.isObjectExpression(node)) {
  // ...
}
if (t.isCallExpression(node) && node.arguments.length) {
  const potentialArrayNode = node.arguments[0];
  if (t.isArrayExpression(potentialArrayNode)) {
    return extractFromArrayExpression(potentialArrayNode, rawCode, opts);
  }
}
```

**Comment by ryan-roemer** [comment]
@ryan-codingintrigue -- Cool! I'll wrap that into the branch I'm working on with regression tests...
