### ISSUE TITLE
Add `babel-traverse` to `package.json` dependencies

### ISSUE THREAD

**Issue by deadcoder0904** [FormidableLabs/inspectpack#55]
It is used at https://github.com/FormidableLabs/inspectpack/blob/master/lib/actions/parse.js#L6 as it makes [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) unusable with [pnpm](https://github.com/pnpm/pnpm)

Relevant issue https://github.com/pnpm/pnpm/issues/1043

**Comment by ryan-roemer** [comment]
Thanks @deadcoder0904 and good catch!

Turns out we had the `eslint-plugin-import` as a dependency, just not enabled...
