### ISSUE TITLE
`better-sqlite3` compiles from source

### ISSUE THREAD

**Issue by Schlesiger** [FormidableLabs/inspectpack#58]
I was using `webpack-dashboard`, but since the 1.x.x releases, it appears `inspectpack` now depends/installs `better-sqlite3`? `better-sqlite3` dependency seems to only include source, and must compile on every npm install. Is there an alternative with prebuilt binaries or can this dependency be omitted somehow? [It appears I'm not the only one who requests this.](https://github.com/JoshuaWise/better-sqlite3/issues/88)

**Comment by ryan-roemer** [comment]
`better-sqlite3` is an `optionalDependencies`, so we're not breaking anyone if the install fails.

We'll definitely accept a PR that has prebuilt binaries or something that still gives up sqlite while omitting the build step.

**Comment by Schlesiger** [comment]
Thanks! Even if my system _can_ run `better-sqlite3` successfully, I just don't want the additional build time. I'd prefer it if the dependency wasn't listed at all, and then the documentation informs users that if they'd like caching, they must include install `better-sqlite3` in their `package.json`.

It boils down to [this issue](https://github.com/npm/npm/issues/14185); we can't yet ignore optional dependencies in `package.json`. If we ever can, then I could ignore `webpack-dashboard` and `inspectpack`'s `optionalDependencies` and this wouldn't be an issue.

**Comment by ryan-roemer** [comment]
Removed library in `inspectpack@^3`.
